import { db } from "./db";
import { categories, brands, products, banners, siteSettings, coupons, pages, users, productVariants, pageLayouts } from "@shared/schema";
import { eq } from "drizzle-orm";
import bcrypt from "bcryptjs";

export async function seedDatabase() {
  const existing = await db.select().from(categories).limit(1);
  if (existing.length > 0) return;

  const catData = [
    { name: "Protein Tozu", slug: "protein-tozu", description: "Whey, Casein, Vegan ve daha fazlasi", image: "https://images.unsplash.com/photo-1593095948071-474c5cc2c755?w=400", sortOrder: 1, parentId: null },
    { name: "Amino Asit & BCAA", slug: "amino-asit-bcaa", description: "BCAA, EAA, Glutamin, Arginin", image: "https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=400", sortOrder: 2, parentId: null },
    { name: "Kreatin", slug: "kreatin", description: "Kreatin Monohidrat, HCL ve karisimlari", image: "https://images.unsplash.com/photo-1594381898411-846e7d193883?w=400", sortOrder: 3, parentId: null },
    { name: "Pre-Workout & Enerji", slug: "pre-workout", description: "Antrenman oncesi takviyeler", image: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400", sortOrder: 4, parentId: null },
    { name: "Kilo & Hacim", slug: "kilo-hacim", description: "Mass Gainer ve karbonhidrat tozlari", image: "https://images.unsplash.com/photo-1532384748853-8f54a8f476e2?w=400", sortOrder: 5, parentId: null },
    { name: "Vitamin & Mineral", slug: "vitamin-mineral", description: "Multivitamin, D vitamini, Omega 3", image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400", sortOrder: 6, parentId: null },
    { name: "Saglik & Yasam", slug: "saglik-yasam", description: "Bagisiklik, eklem sagligi, probiyotik", image: "https://images.unsplash.com/photo-1505576399279-565b52d4ac71?w=400", sortOrder: 7, parentId: null },
    { name: "Diyet & Zayiflama", slug: "diyet-zayiflama", description: "Yag yakicilar, CLA, L-Karnitin", image: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=400", sortOrder: 8, parentId: null },
    { name: "Spor Gidalari", slug: "spor-gidalari", description: "Protein bar, cookie, fisik ezmesi", image: "https://images.unsplash.com/photo-1622484212850-1d462e4a5111?w=400", sortOrder: 9, parentId: null },
    { name: "Spor Aksesuarlari", slug: "spor-aksesuarlari", description: "Shaker, eldiven, bant, mat", image: "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400", sortOrder: 10, parentId: null },
  ];
  const insertedCats = await db.insert(categories).values(catData).returning();

  const brandData = [
    { name: "Optimum Nutrition", slug: "optimum-nutrition", logo: "https://logo.clearbit.com/optimumnutrition.com", sortOrder: 1 },
    { name: "MuscleTech", slug: "muscletech", logo: "https://logo.clearbit.com/muscletech.com", sortOrder: 2 },
    { name: "Dymatize", slug: "dymatize", logo: "https://logo.clearbit.com/dymatize.com", sortOrder: 3 },
    { name: "BSN", slug: "bsn", logo: "https://logo.clearbit.com/bsn.com", sortOrder: 4 },
    { name: "MyProtein", slug: "myprotein", logo: "https://logo.clearbit.com/myprotein.com", sortOrder: 5 },
    { name: "Hardline", slug: "hardline", logo: "https://logo.clearbit.com/hardlinenutrition.com", sortOrder: 6 },
    { name: "Scitec Nutrition", slug: "scitec-nutrition", logo: "https://logo.clearbit.com/scitecnutrition.com", sortOrder: 7 },
    { name: "BioTech USA", slug: "biotech-usa", logo: "https://logo.clearbit.com/biotechusa.com", sortOrder: 8 },
    { name: "Kevin Levrone", slug: "kevin-levrone", logo: "https://logo.clearbit.com/kevinlevrone.com", sortOrder: 9 },
    { name: "Now Foods", slug: "now-foods", logo: "https://logo.clearbit.com/nowfoods.com", sortOrder: 10 },
    { name: "Universal Nutrition", slug: "universal-nutrition", logo: "https://logo.clearbit.com/universalnutrition.com", sortOrder: 11 },
    { name: "Rule1", slug: "rule1", logo: "https://logo.clearbit.com/ruleoneproteins.com", sortOrder: 12 },
  ];
  const insertedBrands = await db.insert(brands).values(brandData).returning();

  const productData = [
    {
      name: "Gold Standard 100% Whey Protein",
      slug: "gold-standard-whey",
      description: "Dunyanin 1 numarali whey protein tozu. Her serviste 24g protein, 5.5g BCAA ve 4g Glutamin icerir. Hizli emilebilir whey protein izolat, konsantre ve peptitler karisimi.",
      shortDescription: "24g protein, 5.5g BCAA per servis",
      price: "1299.00",
      comparePrice: "1599.00",
      categoryId: insertedCats[0].id,
      brandId: insertedBrands[0].id,
      images: ["https://images.unsplash.com/photo-1593095948071-474c5cc2c755?w=600", "https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=600"],
      flavors: ["Cikolata", "Vanilya", "Cilek", "Muz", "Karamel", "Kahve"],
      weights: ["908g", "2.27kg", "4.54kg"],
      stock: 150,
      sku: "ON-GS-001",
      isFeatured: true,
      isBestSeller: true,
      isNewArrival: false,
      tags: ["whey", "protein", "kas-yapimi"],
      rating: "4.8",
      reviewCount: 1250,
      nutritionFacts: { protein: "24g", calories: "120", fat: "1g", carbs: "3g", bcaa: "5.5g", glutamine: "4g" },
      usageInstructions: "1 olcu kasigi (30.4g) 180-240ml su veya sut ile karistirin. Antrenman sonrasi veya gun icerisinde tuketin.",
    },
    {
      name: "Nitro-Tech Whey Gold",
      slug: "nitro-tech-whey-gold",
      description: "MuscleTech'in en saf whey protein formulu. Her serviste 24g ultra premium whey protein izolat ve peptitler icerir.",
      shortDescription: "24g pure whey protein isolate",
      price: "1199.00",
      comparePrice: "1449.00",
      categoryId: insertedCats[0].id,
      brandId: insertedBrands[1].id,
      images: ["https://images.unsplash.com/photo-1594381898411-846e7d193883?w=600"],
      flavors: ["Double Rich Cikolata", "Vanilya", "Cookies & Cream"],
      weights: ["1kg", "2.27kg"],
      stock: 85,
      sku: "MT-NTG-001",
      isFeatured: true,
      isBestSeller: true,
      tags: ["whey", "izolat", "protein"],
      rating: "4.6",
      reviewCount: 890,
      nutritionFacts: { protein: "24g", calories: "130", fat: "2g", carbs: "2g" },
      usageInstructions: "1 olcu kasigi 200ml su ile karistirin.",
    },
    {
      name: "ISO 100 Hydrolyzed Whey Protein",
      slug: "iso-100-hydrolyzed",
      description: "Hidrolize whey protein izolat. Ultra hizli emilim, laktoz ve gluten icermez. Her serviste 25g protein.",
      shortDescription: "25g hidrolize whey protein izolat",
      price: "1599.00",
      comparePrice: "1899.00",
      categoryId: insertedCats[0].id,
      brandId: insertedBrands[2].id,
      images: ["https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600"],
      flavors: ["Cikolata", "Vanilya", "Cilek", "Brownie"],
      weights: ["725g", "1.36kg", "2.27kg"],
      stock: 60,
      sku: "DY-ISO-001",
      isFeatured: true,
      isLactoseFree: true,
      isGlutenFree: true,
      tags: ["hidrolize", "izolat", "protein"],
      rating: "4.9",
      reviewCount: 650,
      nutritionFacts: { protein: "25g", calories: "106", fat: "0g", carbs: "1g" },
      usageInstructions: "1 olcu kasigi 180ml su ile karistirin.",
    },
    {
      name: "Syntha-6 Protein",
      slug: "syntha-6-protein",
      description: "Ultra premium protein matrix. 6 farkli protein kaynagi ile uzun sureli amino asit salimini saglar. Kremsi ve lezzetli.",
      shortDescription: "22g multi-source protein",
      price: "999.00",
      comparePrice: "1249.00",
      categoryId: insertedCats[0].id,
      brandId: insertedBrands[3].id,
      images: ["https://images.unsplash.com/photo-1532384748853-8f54a8f476e2?w=600"],
      flavors: ["Cikolata Milkshake", "Vanilya", "Cilek", "Cookies & Cream"],
      weights: ["1.32kg", "2.27kg"],
      stock: 120,
      sku: "BSN-S6-001",
      isBestSeller: true,
      tags: ["casein", "whey", "multi-protein"],
      rating: "4.5",
      reviewCount: 780,
      nutritionFacts: { protein: "22g", calories: "200", fat: "6g", carbs: "15g" },
    },
    {
      name: "Impact Whey Protein",
      slug: "impact-whey-protein",
      description: "Yuksek kaliteli whey protein konsantre. Uygun fiyatli, 21g protein per servis. 50'den fazla aroma secenegi.",
      shortDescription: "21g protein, 50+ aroma",
      price: "699.00",
      comparePrice: "899.00",
      categoryId: insertedCats[0].id,
      brandId: insertedBrands[4].id,
      images: ["https://images.unsplash.com/photo-1622484212850-1d462e4a5111?w=600"],
      flavors: ["Cikolata", "Vanilya", "Cilek Kremasi", "Salted Caramel", "Muz"],
      weights: ["1kg", "2.5kg", "5kg"],
      stock: 200,
      sku: "MP-IWP-001",
      isFeatured: true,
      isNewArrival: true,
      tags: ["whey", "uygun-fiyat", "protein"],
      rating: "4.4",
      reviewCount: 2100,
      nutritionFacts: { protein: "21g", calories: "103", fat: "1.9g", carbs: "1g" },
    },
    {
      name: "BCAA 4:1:1 Powder",
      slug: "bcaa-411-powder",
      description: "4:1:1 oraninda dallanmis zincirli amino asitler. Kas korumasi ve toparlanma icin ideal.",
      shortDescription: "7g BCAA per servis, 4:1:1 oran",
      price: "449.00",
      comparePrice: "549.00",
      categoryId: insertedCats[1].id,
      brandId: insertedBrands[5].id,
      images: ["https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=600"],
      flavors: ["Karpuz", "Limon", "Portakal", "Orman Meyveli"],
      weights: ["300g", "600g"],
      stock: 90,
      sku: "HL-BCAA-001",
      isFeatured: true,
      tags: ["bcaa", "amino-asit", "toparlanma"],
      rating: "4.3",
      reviewCount: 340,
      nutritionFacts: { leucine: "4g", isoleucine: "1g", valine: "1g" },
    },
    {
      name: "Creatine Monohydrate",
      slug: "creatine-monohydrate-on",
      description: "Saf kreatin monohidrat. Guc ve performans artisi icin kanitlanmis formul. Mikronize partikul boyutu.",
      shortDescription: "5g saf kreatin monohidrat",
      price: "349.00",
      comparePrice: "449.00",
      categoryId: insertedCats[2].id,
      brandId: insertedBrands[0].id,
      images: ["https://images.unsplash.com/photo-1594381898411-846e7d193883?w=600"],
      flavors: ["Aromasiz"],
      weights: ["300g", "600g"],
      stock: 180,
      sku: "ON-CRE-001",
      isBestSeller: true,
      isNewArrival: true,
      tags: ["kreatin", "guc", "performans"],
      rating: "4.7",
      reviewCount: 920,
      nutritionFacts: { creatine: "5g" },
      usageInstructions: "Gunluk 1 olcu kasigi (5g) su veya meyve suyu ile tuketin.",
    },
    {
      name: "C4 Original Pre-Workout",
      slug: "c4-original-pre-workout",
      description: "Amerika'nin 1 numarali pre-workout suplementi. Beta-Alanin, Kreatin Nitrat ve kafein ile explosive enerji.",
      shortDescription: "150mg kafein, Beta-Alanin, NO3-T",
      price: "599.00",
      comparePrice: "749.00",
      categoryId: insertedCats[3].id,
      brandId: insertedBrands[1].id,
      images: ["https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600"],
      flavors: ["Fruit Punch", "Icy Blue Razz", "Watermelon", "Pink Lemonade"],
      weights: ["195g", "390g"],
      stock: 75,
      sku: "CL-C4-001",
      isFeatured: true,
      tags: ["pre-workout", "enerji", "performans"],
      rating: "4.5",
      reviewCount: 560,
      nutritionFacts: { caffeine: "150mg", betaAlanine: "1.6g", creatineNitrate: "1g" },
    },
    {
      name: "Serious Mass Gainer",
      slug: "serious-mass-gainer",
      description: "1250 kalori, 50g protein per servis. Kilo almak isteyenler icin ideal. 25 vitamin ve mineral icerir.",
      shortDescription: "1250 kalori, 50g protein",
      price: "1099.00",
      comparePrice: "1399.00",
      categoryId: insertedCats[4].id,
      brandId: insertedBrands[0].id,
      images: ["https://images.unsplash.com/photo-1532384748853-8f54a8f476e2?w=600"],
      flavors: ["Cikolata", "Vanilya", "Cilek", "Muz"],
      weights: ["2.72kg", "5.44kg"],
      stock: 40,
      sku: "ON-SM-001",
      isBestSeller: true,
      tags: ["gainer", "kilo-alma", "mass"],
      rating: "4.3",
      reviewCount: 430,
      nutritionFacts: { protein: "50g", calories: "1250", carbs: "252g", fat: "4.5g" },
    },
    {
      name: "Omega 3 Fish Oil 1000mg",
      slug: "omega-3-fish-oil",
      description: "Yuksek kaliteli balik yagi. EPA ve DHA iceren omega 3 yag asitleri. Kalp ve beyin sagligi icin.",
      shortDescription: "1000mg balik yagi, EPA+DHA",
      price: "199.00",
      comparePrice: "269.00",
      categoryId: insertedCats[5].id,
      brandId: insertedBrands[9].id,
      images: ["https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600"],
      flavors: [],
      weights: ["100 Kapsul", "200 Kapsul"],
      stock: 250,
      sku: "NF-OM3-001",
      isNewArrival: true,
      tags: ["omega-3", "vitamin", "saglik"],
      rating: "4.6",
      reviewCount: 380,
      nutritionFacts: { omega3: "1000mg", epa: "360mg", dha: "240mg" },
    },
    {
      name: "L-Carnitine 3000 Liquid",
      slug: "l-carnitine-3000",
      description: "Sivi L-Karnitin formulu. Yag yakimini destekler ve enerji uretimini artirir. Lezzetli ve kolay tuketim.",
      shortDescription: "3000mg L-Karnitin per servis",
      price: "349.00",
      comparePrice: "449.00",
      categoryId: insertedCats[7].id,
      brandId: insertedBrands[6].id,
      images: ["https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=600"],
      flavors: ["Portakal", "Limon", "Ananas", "Karpuz"],
      weights: ["500ml", "1000ml"],
      stock: 110,
      sku: "SC-LC-001",
      isFeatured: true,
      tags: ["l-karnitin", "yag-yakici", "diyet"],
      rating: "4.2",
      reviewCount: 290,
      nutritionFacts: { lCarnitine: "3000mg" },
    },
    {
      name: "Protein Bar Box (12 Adet)",
      slug: "protein-bar-box",
      description: "20g protein iceren lezzetli protein barlar. Ara ogun olarak veya antrenman sonrasi tuketilebilir. 12'li kutu.",
      shortDescription: "20g protein per bar, 12'li kutu",
      price: "549.00",
      comparePrice: "699.00",
      categoryId: insertedCats[8].id,
      brandId: insertedBrands[7].id,
      images: ["https://images.unsplash.com/photo-1622484212850-1d462e4a5111?w=600"],
      flavors: ["Cikolata-Karamel", "Cookies & Cream", "Findik"],
      weights: ["12x60g"],
      stock: 65,
      sku: "BT-PB-001",
      isNewArrival: true,
      isSugarFree: true,
      tags: ["protein-bar", "atistirmalik", "spor-gida"],
      rating: "4.4",
      reviewCount: 210,
      nutritionFacts: { protein: "20g", calories: "198", fiber: "7g", sugar: "1g" },
    },
  ];
  await db.insert(products).values(productData);

  const bannerData = [
    {
      title: "Yaz Kampanyasi Basladi!",
      subtitle: "Tum protein tozlarinda %25'e varan indirimler",
      image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1200",
      link: "/kategori/protein-tozu",
      buttonText: "Hemen Al",
      sortOrder: 1,
      type: "hero",
    },
    {
      title: "Yeni Sezon Urunleri",
      subtitle: "En yeni supplement'ler sitemizde",
      image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=1200",
      link: "/urunler?sort=newest",
      buttonText: "Kesfet",
      sortOrder: 2,
      type: "hero",
    },
    {
      title: "500 TL Uzeri Kargo Bedava",
      subtitle: "Hemen siparis verin, ucretsiz kargo firsatini kacirmayin",
      image: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=1200",
      link: "/urunler",
      buttonText: "Alisverise Basla",
      sortOrder: 3,
      type: "hero",
    },
  ];
  await db.insert(banners).values(bannerData);

  const settingsData = [
    { key: "site_name", value: "FitSupp", type: "text" },
    { key: "site_description", value: "Turkiye'nin En Guvenilir Supplement Magazasi", type: "text" },
    { key: "phone", value: "+90 (212) 555 0123", type: "text" },
    { key: "email", value: "info@fitsupp.com", type: "text" },
    { key: "whatsapp", value: "905321234567", type: "text" },
    { key: "address", value: "Levent, Istanbul, Turkiye", type: "text" },
    { key: "free_shipping_threshold", value: "500", type: "number" },
    { key: "announcement_text", value: "500 TL uzeri KARGO BEDAVA | Yeni uyelere %10 hosgeldin indirimi", type: "text" },
    { key: "primary_color", value: "#39FF14", type: "color" },
    { key: "secondary_color", value: "#1a1a1a", type: "color" },
    { key: "accent_color", value: "#39FF14", type: "color" },
    { key: "background_color", value: "#0a0a0a", type: "color" },
    { key: "card_color", value: "#1a1a1a", type: "color" },
    { key: "text_color", value: "#f5f5f5", type: "color" },
    { key: "font_heading", value: "Poppins", type: "text" },
    { key: "font_body", value: "Inter", type: "text" },
    { key: "border_radius", value: "0.5", type: "number" },
    { key: "instagram", value: "https://instagram.com/fitsupp", type: "text" },
    { key: "twitter", value: "https://twitter.com/fitsupp", type: "text" },
    { key: "facebook", value: "https://facebook.com/fitsupp", type: "text" },
    { key: "youtube", value: "https://youtube.com/fitsupp", type: "text" },
    { key: "logo_url", value: "", type: "text" },
    { key: "favicon_url", value: "", type: "text" },
    { key: "seo_title", value: "FitSupp - Türkiye'nin En Güvenilir Supplement Mağazası", type: "text" },
    { key: "seo_description", value: "Orijinal ürün garantisi ile whey protein, kreatin, BCAA, vitamin ve tüm sporcu gıdaları. Hızlı kargo, güvenli ödeme.", type: "text" },
    { key: "seo_keywords", value: "protein tozu, supplement, whey protein, kreatin, bcaa, sporcu gıdası, fitness takviye", type: "text" },
    { key: "og_image", value: "", type: "text" },
    { key: "tiktok", value: "", type: "text" },
    { key: "footer_text", value: "Tüm hakları saklıdır.", type: "text" },
  ];
  await db.insert(siteSettings).values(settingsData);

  await db.insert(coupons).values([
    { code: "HOSGELDIN10", discountType: "percentage", discountValue: "10", minOrderAmount: "200", isActive: true, usageLimit: 1000 },
    { code: "YAZ25", discountType: "percentage", discountValue: "25", minOrderAmount: "500", isActive: true, usageLimit: 500 },
  ]);

  await db.insert(pages).values([
    { title: "Hakkimizda", slug: "hakkimizda", content: "<h2>FitSupp Hakkinda</h2><p>FitSupp, Turkiye'nin lider supplement ve spor gidasi magazasidir. 2020 yilindan bu yana binlerce musteriye hizmet vermekteyiz. Tum urunlerimiz %100 orijinal ve yetkili distributor garantisidir.</p>" },
    { title: "Iade ve Degisim", slug: "iade-degisim", content: "<h2>Iade & Degisim Politikasi</h2><p>14 gun icerisinde kosulsuz iade hakkiniz bulunmaktadir. Urunun acilmamis ve kullanilmamis olmasi gerekmektedir.</p>" },
    { title: "Gizlilik Politikasi", slug: "gizlilik-politikasi", content: "<h2>Gizlilik Politikasi</h2><p>Kisisel verileriniz 6698 sayili KVKK kapsaminda korunmaktadir.</p>" },
    { title: "Kullanim Sartlari", slug: "kullanim-sartlari", content: "<h2>Kullanim Kosullari</h2><p>Sitemizi kullanimda asagidaki kosullari kabul etmis sayilirsiniz.</p>" },
    { title: "KVKK Aydinlatma Metni", slug: "kvkk-aydinlatma", content: "<h2>KVKK Aydinlatma Metni</h2><p>6698 sayili Kisisel Verilerin Korunmasi Kanunu kapsaminda kisisel verilerinizin islenmesine iliskin aydinlatma metnimiz.</p>" },
    { title: "Cerez Politikasi", slug: "cerez-politikasi", content: "<h2>Cerez (Cookie) Politikasi</h2><p>Web sitemizde kullanici deneyimini iyilestirmek ve hizmetlerimizi optimize etmek amaciyla cerezler kullanilmaktadir.</p>" },
  ]);

  const adminPassword = await bcrypt.hash("admin123", 10);
  await db.insert(users).values([
    { username: "admin", email: "admin@fitsupp.com", password: adminPassword, fullName: "Sistem Yöneticisi", role: "super_admin" },
  ]);

  const insertedProducts = await db.select().from(products);
  const wheyProduct = insertedProducts.find(p => p.slug === "gold-standard-whey");
  if (wheyProduct) {
    await db.insert(productVariants).values([
      { productId: wheyProduct.id, flavor: "Cikolata", weight: "908g", sku: "ON-GS-CHO-908", barcode: "7481001200101", price: "1299.00", comparePrice: "1599.00", stock: 50 },
      { productId: wheyProduct.id, flavor: "Cikolata", weight: "2.27kg", sku: "ON-GS-CHO-2270", barcode: "7481001200102", price: "2499.00", comparePrice: "2999.00", stock: 30 },
      { productId: wheyProduct.id, flavor: "Vanilya", weight: "908g", sku: "ON-GS-VAN-908", barcode: "7481001200201", price: "1299.00", comparePrice: "1599.00", stock: 40 },
      { productId: wheyProduct.id, flavor: "Vanilya", weight: "2.27kg", sku: "ON-GS-VAN-2270", barcode: "7481001200202", price: "2499.00", comparePrice: "2999.00", stock: 25 },
      { productId: wheyProduct.id, flavor: "Cilek", weight: "908g", sku: "ON-GS-STR-908", barcode: "7481001200301", price: "1299.00", comparePrice: "1599.00", stock: 20 },
      { productId: wheyProduct.id, flavor: "Muz", weight: "908g", sku: "ON-GS-BAN-908", barcode: "7481001200401", price: "1279.00", comparePrice: "1599.00", stock: 15 },
    ]);
  }

  await db.insert(pageLayouts).values([
    {
      name: "Ana Sayfa Düzeni",
      slug: "homepage",
      blocks: [
        { type: "hero_slider", order: 1, config: {} },
        { type: "advantages_bar", order: 2, config: {} },
        { type: "categories_grid", order: 3, config: { title: "Kategoriler", columns: 5 } },
        { type: "featured_products", order: 4, config: { title: "Öne Çıkan Ürünler", limit: 8 } },
        { type: "banner_strip", order: 5, config: {} },
        { type: "best_sellers", order: 6, config: { title: "Çok Satanlar", limit: 8 } },
        { type: "new_arrivals", order: 7, config: { title: "Yeni Ürünler", limit: 4 } },
        { type: "brands_carousel", order: 8, config: { title: "Markalar" } },
        { type: "newsletter", order: 9, config: { title: "Bülten" } },
      ],
      isActive: true,
    },
  ]);

  console.log("Database seeded successfully!");
}
