import { db } from "./db";
import { categories, brands, products, banners, siteSettings, coupons, pages, users, productVariants, pageLayouts, navigationLinks, bundles, blogCategories, blogPosts } from "@shared/schema";
import { eq } from "drizzle-orm";
import bcrypt from "bcryptjs";

export async function seedDatabase() {
  const existing = await db.select().from(categories).limit(1);
  if (existing.length > 0) return;

  const catData = [
    { name: "Protein Tozu", slug: "protein-tozu", description: "Whey, Casein, Vegan ve daha fazlasi", image: "https://images.unsplash.com/photo-1593095948071-474c5cc2c755?w=400", sortOrder: 1, parentId: null },
    { name: "Amino Asit & BCAA", slug: "amino-asit-bcaa", description: "BCAA, EAA, Glutamin, Arginin", image: "https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=400", sortOrder: 2, parentId: null },
    { name: "Kreatin", slug: "kreatin", description: "Kreatin Monohidrat, HCL ve karisimlari", image: "https://images.unsplash.com/photo-1594381898411-846e7d193883?w=400", sortOrder: 3, parentId: null },
    { name: "Pre-Workout & Enerji", slug: "pre-workout", description: "Antrenman oncesi takviyeler", image: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400", sortOrder: 4, parentId: null },
    { name: "Kilo & Hacim", slug: "kilo-hacim", description: "Mass Gainer ve karbonhidrat tozlari", image: "https://images.unsplash.com/photo-1532384748853-8f54a8f476e2?w=400", sortOrder: 5, parentId: null },
    { name: "Vitamin & Mineral", slug: "vitamin-mineral", description: "Multivitamin, D vitamini, Omega 3", image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400", sortOrder: 6, parentId: null },
    { name: "Saglik & Yasam", slug: "saglik-yasam", description: "Bagisiklik, eklem sagligi, probiyotik", image: "https://images.unsplash.com/photo-1505576399279-565b52d4ac71?w=400", sortOrder: 7, parentId: null },
    { name: "Diyet & Zayiflama", slug: "diyet-zayiflama", description: "Yag yakicilar, CLA, L-Karnitin", image: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=400", sortOrder: 8, parentId: null },
    { name: "Spor Gidalari", slug: "spor-gidalari", description: "Protein bar, cookie, fisik ezmesi", image: "https://images.unsplash.com/photo-1622484212850-1d462e4a5111?w=400", sortOrder: 9, parentId: null },
    { name: "Spor Aksesuarlari", slug: "spor-aksesuarlari", description: "Shaker, eldiven, bant, mat", image: "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400", sortOrder: 10, parentId: null },
  ];
  const insertedCats = await db.insert(categories).values(catData).returning();

  const brandData = [
    { name: "Optimum Nutrition", slug: "optimum-nutrition", logo: "https://logo.clearbit.com/optimumnutrition.com", sortOrder: 1 },
    { name: "MuscleTech", slug: "muscletech", logo: "https://logo.clearbit.com/muscletech.com", sortOrder: 2 },
    { name: "Dymatize", slug: "dymatize", logo: "https://logo.clearbit.com/dymatize.com", sortOrder: 3 },
    { name: "BSN", slug: "bsn", logo: "https://logo.clearbit.com/bsn.com", sortOrder: 4 },
    { name: "MyProtein", slug: "myprotein", logo: "https://logo.clearbit.com/myprotein.com", sortOrder: 5 },
    { name: "Hardline", slug: "hardline", logo: "https://logo.clearbit.com/hardlinenutrition.com", sortOrder: 6 },
    { name: "Scitec Nutrition", slug: "scitec-nutrition", logo: "https://logo.clearbit.com/scitecnutrition.com", sortOrder: 7 },
    { name: "BioTech USA", slug: "biotech-usa", logo: "https://logo.clearbit.com/biotechusa.com", sortOrder: 8 },
    { name: "Kevin Levrone", slug: "kevin-levrone", logo: "https://logo.clearbit.com/kevinlevrone.com", sortOrder: 9 },
    { name: "Now Foods", slug: "now-foods", logo: "https://logo.clearbit.com/nowfoods.com", sortOrder: 10 },
    { name: "Universal Nutrition", slug: "universal-nutrition", logo: "https://logo.clearbit.com/universalnutrition.com", sortOrder: 11 },
    { name: "Rule1", slug: "rule1", logo: "https://logo.clearbit.com/ruleoneproteins.com", sortOrder: 12 },
  ];
  const insertedBrands = await db.insert(brands).values(brandData).returning();

  const productData = [
    {
      name: "Gold Standard 100% Whey Protein",
      slug: "gold-standard-whey",
      description: "Dunyanin 1 numarali whey protein tozu. Her serviste 24g protein, 5.5g BCAA ve 4g Glutamin icerir. Hizli emilebilir whey protein izolat, konsantre ve peptitler karisimi.",
      shortDescription: "24g protein, 5.5g BCAA per servis",
      price: "1299.00",
      comparePrice: "1599.00",
      categoryId: insertedCats[0].id,
      brandId: insertedBrands[0].id,
      images: ["https://images.unsplash.com/photo-1593095948071-474c5cc2c755?w=600", "https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=600"],
      flavors: ["Cikolata", "Vanilya", "Cilek", "Muz", "Karamel", "Kahve"],
      weights: ["908g", "2.27kg", "4.54kg"],
      stock: 150,
      sku: "ON-GS-001",
      isFeatured: true,
      isBestSeller: true,
      isNewArrival: false,
      tags: ["whey", "protein", "kas-yapimi"],
      rating: "4.8",
      reviewCount: 1250,
      nutritionFacts: { protein: "24g", calories: "120", fat: "1g", carbs: "3g", bcaa: "5.5g", glutamine: "4g" },
      usageInstructions: "1 olcu kasigi (30.4g) 180-240ml su veya sut ile karistirin. Antrenman sonrasi veya gun icerisinde tuketin.",
    },
    {
      name: "Nitro-Tech Whey Gold",
      slug: "nitro-tech-whey-gold",
      description: "MuscleTech'in en saf whey protein formulu. Her serviste 24g ultra premium whey protein izolat ve peptitler icerir.",
      shortDescription: "24g pure whey protein isolate",
      price: "1199.00",
      comparePrice: "1449.00",
      categoryId: insertedCats[0].id,
      brandId: insertedBrands[1].id,
      images: ["https://images.unsplash.com/photo-1594381898411-846e7d193883?w=600"],
      flavors: ["Double Rich Cikolata", "Vanilya", "Cookies & Cream"],
      weights: ["1kg", "2.27kg"],
      stock: 85,
      sku: "MT-NTG-001",
      isFeatured: true,
      isBestSeller: true,
      tags: ["whey", "izolat", "protein"],
      rating: "4.6",
      reviewCount: 890,
      nutritionFacts: { protein: "24g", calories: "130", fat: "2g", carbs: "2g" },
      usageInstructions: "1 olcu kasigi 200ml su ile karistirin.",
    },
    {
      name: "ISO 100 Hydrolyzed Whey Protein",
      slug: "iso-100-hydrolyzed",
      description: "Hidrolize whey protein izolat. Ultra hizli emilim, laktoz ve gluten icermez. Her serviste 25g protein.",
      shortDescription: "25g hidrolize whey protein izolat",
      price: "1599.00",
      comparePrice: "1899.00",
      categoryId: insertedCats[0].id,
      brandId: insertedBrands[2].id,
      images: ["https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600"],
      flavors: ["Cikolata", "Vanilya", "Cilek", "Brownie"],
      weights: ["725g", "1.36kg", "2.27kg"],
      stock: 60,
      sku: "DY-ISO-001",
      isFeatured: true,
      isLactoseFree: true,
      isGlutenFree: true,
      tags: ["hidrolize", "izolat", "protein"],
      rating: "4.9",
      reviewCount: 650,
      nutritionFacts: { protein: "25g", calories: "106", fat: "0g", carbs: "1g" },
      usageInstructions: "1 olcu kasigi 180ml su ile karistirin.",
    },
    {
      name: "Syntha-6 Protein",
      slug: "syntha-6-protein",
      description: "Ultra premium protein matrix. 6 farkli protein kaynagi ile uzun sureli amino asit salimini saglar. Kremsi ve lezzetli.",
      shortDescription: "22g multi-source protein",
      price: "999.00",
      comparePrice: "1249.00",
      categoryId: insertedCats[0].id,
      brandId: insertedBrands[3].id,
      images: ["https://images.unsplash.com/photo-1532384748853-8f54a8f476e2?w=600"],
      flavors: ["Cikolata Milkshake", "Vanilya", "Cilek", "Cookies & Cream"],
      weights: ["1.32kg", "2.27kg"],
      stock: 120,
      sku: "BSN-S6-001",
      isBestSeller: true,
      tags: ["casein", "whey", "multi-protein"],
      rating: "4.5",
      reviewCount: 780,
      nutritionFacts: { protein: "22g", calories: "200", fat: "6g", carbs: "15g" },
    },
    {
      name: "Impact Whey Protein",
      slug: "impact-whey-protein",
      description: "Yuksek kaliteli whey protein konsantre. Uygun fiyatli, 21g protein per servis. 50'den fazla aroma secenegi.",
      shortDescription: "21g protein, 50+ aroma",
      price: "699.00",
      comparePrice: "899.00",
      categoryId: insertedCats[0].id,
      brandId: insertedBrands[4].id,
      images: ["https://images.unsplash.com/photo-1622484212850-1d462e4a5111?w=600"],
      flavors: ["Cikolata", "Vanilya", "Cilek Kremasi", "Salted Caramel", "Muz"],
      weights: ["1kg", "2.5kg", "5kg"],
      stock: 200,
      sku: "MP-IWP-001",
      isFeatured: true,
      isNewArrival: true,
      tags: ["whey", "uygun-fiyat", "protein"],
      rating: "4.4",
      reviewCount: 2100,
      nutritionFacts: { protein: "21g", calories: "103", fat: "1.9g", carbs: "1g" },
    },
    {
      name: "BCAA 4:1:1 Powder",
      slug: "bcaa-411-powder",
      description: "4:1:1 oraninda dallanmis zincirli amino asitler. Kas korumasi ve toparlanma icin ideal.",
      shortDescription: "7g BCAA per servis, 4:1:1 oran",
      price: "449.00",
      comparePrice: "549.00",
      categoryId: insertedCats[1].id,
      brandId: insertedBrands[5].id,
      images: ["https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=600"],
      flavors: ["Karpuz", "Limon", "Portakal", "Orman Meyveli"],
      weights: ["300g", "600g"],
      stock: 90,
      sku: "HL-BCAA-001",
      isFeatured: true,
      tags: ["bcaa", "amino-asit", "toparlanma"],
      rating: "4.3",
      reviewCount: 340,
      nutritionFacts: { leucine: "4g", isoleucine: "1g", valine: "1g" },
    },
    {
      name: "Creatine Monohydrate",
      slug: "creatine-monohydrate-on",
      description: "Saf kreatin monohidrat. Guc ve performans artisi icin kanitlanmis formul. Mikronize partikul boyutu.",
      shortDescription: "5g saf kreatin monohidrat",
      price: "349.00",
      comparePrice: "449.00",
      categoryId: insertedCats[2].id,
      brandId: insertedBrands[0].id,
      images: ["https://images.unsplash.com/photo-1594381898411-846e7d193883?w=600"],
      flavors: ["Aromasiz"],
      weights: ["300g", "600g"],
      stock: 180,
      sku: "ON-CRE-001",
      isBestSeller: true,
      isNewArrival: true,
      tags: ["kreatin", "guc", "performans"],
      rating: "4.7",
      reviewCount: 920,
      nutritionFacts: { creatine: "5g" },
      usageInstructions: "Gunluk 1 olcu kasigi (5g) su veya meyve suyu ile tuketin.",
    },
    {
      name: "C4 Original Pre-Workout",
      slug: "c4-original-pre-workout",
      description: "Amerika'nin 1 numarali pre-workout suplementi. Beta-Alanin, Kreatin Nitrat ve kafein ile explosive enerji.",
      shortDescription: "150mg kafein, Beta-Alanin, NO3-T",
      price: "599.00",
      comparePrice: "749.00",
      categoryId: insertedCats[3].id,
      brandId: insertedBrands[1].id,
      images: ["https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600"],
      flavors: ["Fruit Punch", "Icy Blue Razz", "Watermelon", "Pink Lemonade"],
      weights: ["195g", "390g"],
      stock: 75,
      sku: "CL-C4-001",
      isFeatured: true,
      tags: ["pre-workout", "enerji", "performans"],
      rating: "4.5",
      reviewCount: 560,
      nutritionFacts: { caffeine: "150mg", betaAlanine: "1.6g", creatineNitrate: "1g" },
    },
    {
      name: "Serious Mass Gainer",
      slug: "serious-mass-gainer",
      description: "1250 kalori, 50g protein per servis. Kilo almak isteyenler icin ideal. 25 vitamin ve mineral icerir.",
      shortDescription: "1250 kalori, 50g protein",
      price: "1099.00",
      comparePrice: "1399.00",
      categoryId: insertedCats[4].id,
      brandId: insertedBrands[0].id,
      images: ["https://images.unsplash.com/photo-1532384748853-8f54a8f476e2?w=600"],
      flavors: ["Cikolata", "Vanilya", "Cilek", "Muz"],
      weights: ["2.72kg", "5.44kg"],
      stock: 40,
      sku: "ON-SM-001",
      isBestSeller: true,
      tags: ["gainer", "kilo-alma", "mass"],
      rating: "4.3",
      reviewCount: 430,
      nutritionFacts: { protein: "50g", calories: "1250", carbs: "252g", fat: "4.5g" },
    },
    {
      name: "Omega 3 Fish Oil 1000mg",
      slug: "omega-3-fish-oil",
      description: "Yuksek kaliteli balik yagi. EPA ve DHA iceren omega 3 yag asitleri. Kalp ve beyin sagligi icin.",
      shortDescription: "1000mg balik yagi, EPA+DHA",
      price: "199.00",
      comparePrice: "269.00",
      categoryId: insertedCats[5].id,
      brandId: insertedBrands[9].id,
      images: ["https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600"],
      flavors: [],
      weights: ["100 Kapsul", "200 Kapsul"],
      stock: 250,
      sku: "NF-OM3-001",
      isNewArrival: true,
      tags: ["omega-3", "vitamin", "saglik"],
      rating: "4.6",
      reviewCount: 380,
      nutritionFacts: { omega3: "1000mg", epa: "360mg", dha: "240mg" },
    },
    {
      name: "L-Carnitine 3000 Liquid",
      slug: "l-carnitine-3000",
      description: "Sivi L-Karnitin formulu. Yag yakimini destekler ve enerji uretimini artirir. Lezzetli ve kolay tuketim.",
      shortDescription: "3000mg L-Karnitin per servis",
      price: "349.00",
      comparePrice: "449.00",
      categoryId: insertedCats[7].id,
      brandId: insertedBrands[6].id,
      images: ["https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=600"],
      flavors: ["Portakal", "Limon", "Ananas", "Karpuz"],
      weights: ["500ml", "1000ml"],
      stock: 110,
      sku: "SC-LC-001",
      isFeatured: true,
      tags: ["l-karnitin", "yag-yakici", "diyet"],
      rating: "4.2",
      reviewCount: 290,
      nutritionFacts: { lCarnitine: "3000mg" },
    },
    {
      name: "Protein Bar Box (12 Adet)",
      slug: "protein-bar-box",
      description: "20g protein iceren lezzetli protein barlar. Ara ogun olarak veya antrenman sonrasi tuketilebilir. 12'li kutu.",
      shortDescription: "20g protein per bar, 12'li kutu",
      price: "549.00",
      comparePrice: "699.00",
      categoryId: insertedCats[8].id,
      brandId: insertedBrands[7].id,
      images: ["https://images.unsplash.com/photo-1622484212850-1d462e4a5111?w=600"],
      flavors: ["Cikolata-Karamel", "Cookies & Cream", "Findik"],
      weights: ["12x60g"],
      stock: 65,
      sku: "BT-PB-001",
      isNewArrival: true,
      isSugarFree: true,
      tags: ["protein-bar", "atistirmalik", "spor-gida"],
      rating: "4.4",
      reviewCount: 210,
      nutritionFacts: { protein: "20g", calories: "198", fiber: "7g", sugar: "1g" },
    },
  ];
  await db.insert(products).values(productData);

  const bannerData = [
    {
      title: "Yaz Kampanyasi Basladi!",
      subtitle: "Tum protein tozlarinda %25'e varan indirimler",
      image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1200",
      link: "/kategori/protein-tozu",
      buttonText: "Hemen Al",
      sortOrder: 1,
      type: "hero",
    },
    {
      title: "Yeni Sezon Urunleri",
      subtitle: "En yeni supplement'ler sitemizde",
      image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=1200",
      link: "/urunler?sort=newest",
      buttonText: "Kesfet",
      sortOrder: 2,
      type: "hero",
    },
    {
      title: "500 TL Uzeri Kargo Bedava",
      subtitle: "Hemen siparis verin, ucretsiz kargo firsatini kacirmayin",
      image: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=1200",
      link: "/urunler",
      buttonText: "Alisverise Basla",
      sortOrder: 3,
      type: "hero",
    },
  ];
  await db.insert(banners).values(bannerData);

  const settingsData = [
    { key: "site_name", value: "FitSupp", type: "text" },
    { key: "site_description", value: "Turkiye'nin En Guvenilir Supplement Magazasi", type: "text" },
    { key: "phone", value: "+90 (212) 555 0123", type: "text" },
    { key: "email", value: "info@fitsupp.com", type: "text" },
    { key: "whatsapp", value: "905321234567", type: "text" },
    { key: "address", value: "Levent, Istanbul, Turkiye", type: "text" },
    { key: "free_shipping_threshold", value: "500", type: "number" },
    { key: "announcement_text", value: "500 TL uzeri KARGO BEDAVA | Yeni uyelere %10 hosgeldin indirimi", type: "text" },
    { key: "primary_color", value: "#39FF14", type: "color" },
    { key: "secondary_color", value: "#1a1a1a", type: "color" },
    { key: "accent_color", value: "#39FF14", type: "color" },
    { key: "background_color", value: "#0a0a0a", type: "color" },
    { key: "card_color", value: "#1a1a1a", type: "color" },
    { key: "text_color", value: "#f5f5f5", type: "color" },
    { key: "font_heading", value: "Poppins", type: "text" },
    { key: "font_body", value: "Inter", type: "text" },
    { key: "border_radius", value: "0.5", type: "number" },
    { key: "instagram", value: "https://instagram.com/fitsupp", type: "text" },
    { key: "twitter", value: "https://twitter.com/fitsupp", type: "text" },
    { key: "facebook", value: "https://facebook.com/fitsupp", type: "text" },
    { key: "youtube", value: "https://youtube.com/fitsupp", type: "text" },
    { key: "logo_url", value: "", type: "text" },
    { key: "favicon_url", value: "", type: "text" },
    { key: "seo_title", value: "FitSupp - Türkiye'nin En Güvenilir Supplement Mağazası", type: "text" },
    { key: "seo_description", value: "Orijinal ürün garantisi ile whey protein, kreatin, BCAA, vitamin ve tüm sporcu gıdaları. Hızlı kargo, güvenli ödeme.", type: "text" },
    { key: "seo_keywords", value: "protein tozu, supplement, whey protein, kreatin, bcaa, sporcu gıdası, fitness takviye", type: "text" },
    { key: "og_image", value: "", type: "text" },
    { key: "tiktok", value: "", type: "text" },
    { key: "footer_text", value: "Tüm hakları saklıdır.", type: "text" },
  ];
  await db.insert(siteSettings).values(settingsData);

  await db.insert(coupons).values([
    { code: "HOSGELDIN10", discountType: "percentage", discountValue: "10", minOrderAmount: "200", isActive: true, usageLimit: 1000 },
    { code: "YAZ25", discountType: "percentage", discountValue: "25", minOrderAmount: "500", isActive: true, usageLimit: 500 },
  ]);

  await db.insert(pages).values([
    { title: "Hakkimizda", slug: "hakkimizda", content: "<h2>FitSupp Hakkinda</h2><p>FitSupp, Turkiye'nin lider supplement ve spor gidasi magazasidir. 2020 yilindan bu yana binlerce musteriye hizmet vermekteyiz. Tum urunlerimiz %100 orijinal ve yetkili distributor garantisidir.</p>" },
    { title: "Iade ve Degisim", slug: "iade-degisim", content: "<h2>Iade & Degisim Politikasi</h2><p>14 gun icerisinde kosulsuz iade hakkiniz bulunmaktadir. Urunun acilmamis ve kullanilmamis olmasi gerekmektedir.</p>" },
    { title: "Gizlilik Politikasi", slug: "gizlilik-politikasi", content: "<h2>Gizlilik Politikasi</h2><p>Kisisel verileriniz 6698 sayili KVKK kapsaminda korunmaktadir.</p>" },
    { title: "Kullanim Sartlari", slug: "kullanim-sartlari", content: "<h2>Kullanim Kosullari</h2><p>Sitemizi kullanimda asagidaki kosullari kabul etmis sayilirsiniz.</p>" },
    { title: "KVKK Aydinlatma Metni", slug: "kvkk-aydinlatma", content: "<h2>KVKK Aydinlatma Metni</h2><p>6698 sayili Kisisel Verilerin Korunmasi Kanunu kapsaminda kisisel verilerinizin islenmesine iliskin aydinlatma metnimiz.</p>" },
    { title: "Cerez Politikasi", slug: "cerez-politikasi", content: "<h2>Cerez (Cookie) Politikasi</h2><p>Web sitemizde kullanici deneyimini iyilestirmek ve hizmetlerimizi optimize etmek amaciyla cerezler kullanilmaktadir.</p>" },
  ]);

  const adminPassword = await bcrypt.hash("admin123", 10);
  await db.insert(users).values([
    { username: "admin", email: "admin@fitsupp.com", password: adminPassword, fullName: "Sistem Yöneticisi", role: "super_admin" },
  ]);

  const insertedProducts = await db.select().from(products);
  const wheyProduct = insertedProducts.find(p => p.slug === "gold-standard-whey");
  if (wheyProduct) {
    await db.insert(productVariants).values([
      { productId: wheyProduct.id, flavor: "Cikolata", weight: "908g", sku: "ON-GS-CHO-908", barcode: "7481001200101", price: "1299.00", comparePrice: "1599.00", stock: 50 },
      { productId: wheyProduct.id, flavor: "Cikolata", weight: "2.27kg", sku: "ON-GS-CHO-2270", barcode: "7481001200102", price: "2499.00", comparePrice: "2999.00", stock: 30 },
      { productId: wheyProduct.id, flavor: "Vanilya", weight: "908g", sku: "ON-GS-VAN-908", barcode: "7481001200201", price: "1299.00", comparePrice: "1599.00", stock: 40 },
      { productId: wheyProduct.id, flavor: "Vanilya", weight: "2.27kg", sku: "ON-GS-VAN-2270", barcode: "7481001200202", price: "2499.00", comparePrice: "2999.00", stock: 25 },
      { productId: wheyProduct.id, flavor: "Cilek", weight: "908g", sku: "ON-GS-STR-908", barcode: "7481001200301", price: "1299.00", comparePrice: "1599.00", stock: 20 },
      { productId: wheyProduct.id, flavor: "Muz", weight: "908g", sku: "ON-GS-BAN-908", barcode: "7481001200401", price: "1279.00", comparePrice: "1599.00", stock: 15 },
    ]);
  }

  await db.insert(pageLayouts).values([
    {
      name: "Ana Sayfa Düzeni",
      slug: "homepage",
      blocks: [
        { type: "hero_slider", order: 1, config: {} },
        { type: "advantages_bar", order: 2, config: {} },
        { type: "categories_grid", order: 3, config: { title: "Kategoriler", columns: 5 } },
        { type: "featured_products", order: 4, config: { title: "Öne Çıkan Ürünler", limit: 8 } },
        { type: "wizard_promo", order: 5, config: {} },
        { type: "best_sellers", order: 6, config: { title: "Çok Satanlar", limit: 8 } },
        { type: "new_arrivals", order: 7, config: { title: "Yeni Ürünler", limit: 4 } },
        { type: "campaigns", order: 8, config: {} },
        { type: "brands_carousel", order: 9, config: { title: "Markalar" } },
        { type: "testimonials", order: 10, config: {} },
        { type: "newsletter", order: 11, config: { title: "Bülten" } },
      ],
      isActive: true,
    },
  ]);

  await db.insert(navigationLinks).values([
    { label: "Ana Sayfa", url: "/", position: "header", sortOrder: 1 },
    { label: "Ürünler", url: "/urunler", position: "header", sortOrder: 2 },
    { label: "Kategoriler", url: "#", position: "header", sortOrder: 3 },
    { label: "Markalar", url: "/markalar", position: "header", sortOrder: 4 },
    { label: "Supplement Sihirbazı", url: "/supplement-sihirbazi", position: "header", sortOrder: 5, icon: "sparkles" },
    { label: "Blog", url: "/blog", position: "header", sortOrder: 6 },
  ]);

  const allProductsList = await db.select().from(products);
  const wheyProd = allProductsList.find(p => p.slug === "gold-standard-whey");
  const creatineProd = allProductsList.find(p => p.slug === "creatine-monohydrate-on");
  const bcaaProd = allProductsList.find(p => p.slug === "bcaa-411-powder");
  const preworkoutProd = allProductsList.find(p => p.slug === "c4-original-pre-workout");
  const gainerProd = allProductsList.find(p => p.slug === "serious-mass-gainer");
  const lCarnitineProd = allProductsList.find(p => p.slug === "l-carnitine-3000");
  const omegaProd = allProductsList.find(p => p.slug === "omega-3-fish-oil");
  const impactWhey = allProductsList.find(p => p.slug === "impact-whey-protein");

  if (wheyProd && creatineProd && bcaaProd && preworkoutProd) {
    await db.insert(bundles).values([
      {
        name: "Kas Kazanım Paketi",
        slug: "kas-kazanim-paketi",
        description: "Kas yapımı için ideal kombinasyon. Whey Protein + Kreatin + BCAA ile maksimum kas gelişimi.",
        image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600",
        goalTags: ["kas_kazanimi", "bulk", "muscle_gain", "kas"],
        items: [
          { productId: wheyProd.id, quantity: 1 },
          { productId: creatineProd.id, quantity: 1 },
          { productId: bcaaProd.id, quantity: 1 },
        ],
        discountPercent: 15,
        price: "1799.00",
        comparePrice: "2097.00",
        sortOrder: 1,
      },
      {
        name: "Performans Paketi",
        slug: "performans-paketi",
        description: "Antrenman performansınızı zirveye taşıyın. Pre-workout + Kreatin + BCAA kombinasyonu.",
        image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600",
        goalTags: ["performans", "performance", "guc", "strength"],
        items: [
          { productId: preworkoutProd.id, quantity: 1 },
          { productId: creatineProd.id, quantity: 1 },
          { productId: bcaaProd.id, quantity: 1 },
        ],
        discountPercent: 12,
        price: "1199.00",
        comparePrice: "1397.00",
        sortOrder: 2,
      },
      ...(gainerProd && omegaProd ? [{
        name: "Kilo Alma Paketi",
        slug: "kilo-alma-paketi",
        description: "Sağlıklı kilo almak isteyenler için. Mass gainer + Omega 3 + Kreatin ile hacim kazanımı.",
        image: "https://images.unsplash.com/photo-1532384748853-8f54a8f476e2?w=600",
        goalTags: ["kilo_alma", "weight_gain", "bulk"],
        items: [
          { productId: gainerProd.id, quantity: 1 },
          { productId: creatineProd.id, quantity: 1 },
          { productId: omegaProd.id, quantity: 1 },
        ],
        discountPercent: 10,
        price: "1399.00",
        comparePrice: "1647.00",
        sortOrder: 3,
      }] : []),
      ...(lCarnitineProd && impactWhey ? [{
        name: "Yağ Yakım Paketi",
        slug: "yag-yakim-paketi",
        description: "Yağ yakımını destekleyen ideal kombinasyon. L-Karnitin + Protein + BCAA.",
        image: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=600",
        goalTags: ["yag_yakim", "cut", "fat_loss", "diyet", "definasyon"],
        items: [
          { productId: lCarnitineProd.id, quantity: 1 },
          { productId: impactWhey.id, quantity: 1 },
          { productId: bcaaProd.id, quantity: 1 },
        ],
        discountPercent: 12,
        price: "1299.00",
        comparePrice: "1497.00",
        sortOrder: 4,
      }] : []),
      ...(omegaProd ? [{
        name: "Genel Sağlık Paketi",
        slug: "genel-saglik-paketi",
        description: "Genel sağlık ve bağışıklık için temel takviyeler. Omega 3 + Protein + Kreatin.",
        image: "https://images.unsplash.com/photo-1505576399279-565b52d4ac71?w=600",
        goalTags: ["genel_saglik", "health", "saglik", "wellness"],
        items: [
          { productId: omegaProd.id, quantity: 1 },
          { productId: impactWhey?.id || wheyProd.id, quantity: 1 },
          { productId: creatineProd.id, quantity: 1 },
        ],
        discountPercent: 10,
        price: "1149.00",
        comparePrice: "1347.00",
        sortOrder: 5,
      }] : []),
    ]);
  }

  const insertedBlogCats = await db.insert(blogCategories).values([
    { name: "Beslenme", slug: "beslenme", description: "Sağlıklı beslenme ve diyet rehberleri", sortOrder: 1 },
    { name: "Antrenman", slug: "antrenman", description: "Egzersiz programları ve antrenman ipuçları", sortOrder: 2 },
    { name: "Supplement Rehberi", slug: "supplement-rehberi", description: "Takviye kullanım rehberleri ve karşılaştırmalar", sortOrder: 3 },
    { name: "Sağlık", slug: "saglik", description: "Genel sağlık ve yaşam kalitesi", sortOrder: 4 },
  ]).returning();

  const beslenmeC = insertedBlogCats.find(c => c.slug === "beslenme");
  const antrenmanC = insertedBlogCats.find(c => c.slug === "antrenman");
  const supplementC = insertedBlogCats.find(c => c.slug === "supplement-rehberi");
  const saglikC = insertedBlogCats.find(c => c.slug === "saglik");

  await db.insert(blogPosts).values([
    {
      title: "Whey Protein Nedir? Kapsamlı Rehber",
      slug: "whey-protein-nedir-kapsamli-rehber",
      excerpt: "Whey protein türleri, faydaları, kullanım zamanı ve doğru seçim rehberi. Konsantre, izolat ve hidrolizat arasındaki farklar.",
      content: `<h2>Whey Protein Nedir?</h2><p>Whey protein, sütten peynir üretimi sırasında elde edilen bir yan üründür. Yüksek biyolojik değere sahip olan whey protein, tüm esansiyel amino asitleri içerir ve vücut tarafından hızla emilir.</p><h3>Whey Protein Türleri</h3><h4>1. Whey Protein Konsantre (WPC)</h4><p>En yaygın ve ekonomik whey protein türüdür. Protein oranı %70-80 arasındadır. Laktoz ve yağ içerebilir ancak biyoaktif bileşenler korunur.</p><h4>2. Whey Protein İzolat (WPI)</h4><p>Ekstra filtrasyon sürecinden geçirilmiş, %90+ protein içeren saf formüldür. Laktoz ve yağ oranı minimumda tutulur. Laktoz hassasiyeti olanlar için idealdir.</p><h4>3. Whey Protein Hidrolizat (WPH)</h4><p>Enzimatik olarak ön-sindirime uğratılmış, en hızlı emilen whey protein türüdür. Genellikle medikal ve sporcu odaklı ürünlerde kullanılır.</p><h3>Ne Zaman Kullanmalı?</h3><p>En etkili kullanım zamanları:</p><ul><li>Antrenman sonrası 30 dakika içinde (anabolik pencere)</li><li>Sabah kahvaltıda protein takviyesi olarak</li><li>Öğün aralarında atıştırmalık yerine</li></ul><h3>Günlük Doz</h3><p>Genel öneri: Kilogram başına 1.6-2.2g protein alımı hedeflenmeli. Örneğin 80kg bir birey günde 128-176g protein almalıdır. Whey protein ile günde 1-3 ölçek kaşığı (25-75g protein) tüketilebilir.</p>`,
      coverImage: "https://images.unsplash.com/photo-1593095948071-474c5cc2c755?w=800",
      categoryId: supplementC?.id || null,
      authorId: null,
      authorName: "FitSupp Uzman Ekibi",
      authorAvatar: null,
      tags: ["whey-protein", "protein", "supplement", "kas-yapimi"],
      readingTime: 5,
      isPublished: true,
      isFeatured: true,
      publishedAt: new Date(),
    },
    {
      title: "Yeni Başlayanlar İçin Fitness Programı",
      slug: "yeni-baslayanlar-icin-fitness-programi",
      excerpt: "Spor salonuna ilk adımınızı atıyorsanız bu 8 haftalık program tam size göre. Temel hareketler ve progresyon rehberi.",
      content: `<h2>Yeni Başlayanlar İçin 8 Haftalık Program</h2><p>Fitness yolculuğunuza doğru bir başlangıç yapmak, uzun vadeli başarı için kritik öneme sahiptir. Bu program, temel bileşik hareketlere odaklanarak vücudunuzu sistematik olarak geliştirecektir.</p><h3>Hafta 1-4: Temel Oluşturma</h3><h4>A Günü (Pazartesi/Perşembe)</h4><ul><li>Squat: 3x10</li><li>Bench Press: 3x10</li><li>Barbell Row: 3x10</li><li>Overhead Press: 3x8</li><li>Plank: 3x30sn</li></ul><h4>B Günü (Salı/Cuma)</h4><ul><li>Deadlift: 3x8</li><li>Dumbbell Press: 3x10</li><li>Lat Pulldown: 3x10</li><li>Leg Press: 3x12</li><li>Bicycle Crunch: 3x15</li></ul><h3>Hafta 5-8: Yoğunluk Artışı</h3><p>Aynı hareketleri 4x set olarak uygulayın. Ağırlıkları %10-15 artırın. Her antrenmanda en az bir tekrar veya 2.5kg artış hedefleyin.</p><h3>Beslenme Önerileri</h3><p>Protein alımınız kilogram başına en az 1.6g olmalıdır. Antrenman sonrası 30 dakika içinde whey protein tüketin. Günde en az 3 litre su için.</p>`,
      coverImage: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800",
      categoryId: antrenmanC?.id || null,
      authorId: null,
      authorName: "FitSupp Uzman Ekibi",
      authorAvatar: null,
      tags: ["fitness", "antrenman", "yeni-baslayan", "program"],
      readingTime: 6,
      isPublished: true,
      isFeatured: true,
      publishedAt: new Date(),
    },
    {
      title: "Kas Yapımı İçin En İyi 10 Besin",
      slug: "kas-yapimi-icin-en-iyi-10-besin",
      excerpt: "Kas gelişiminizi hızlandıracak en etkili besinler ve her birinin kas yapımına katkıları.",
      content: `<h2>Kas Yapımı İçin Beslenme</h2><p>Doğru beslenme, kas yapımının temel taşıdır. İşte kas gelişiminizi destekleyecek en etkili 10 besin:</p><h3>1. Yumurta</h3><p>Biyolojik değeri en yüksek protein kaynağı. Bir yumurta yaklaşık 6g yüksek kaliteli protein içerir. Lösin amino asidi bakımından zengindir.</p><h3>2. Tavuk Göğsü</h3><p>100g pişmiş tavuk göğsünde yaklaşık 31g protein bulunur. Düşük yağlı, yüksek proteinli yapısıyla en popüler kas yapım besinidir.</p><h3>3. Somon</h3><p>Hem yüksek kaliteli protein hem de omega-3 yağ asitleri içerir. Kas inflamasyonunu azaltarak toparlanmayı hızlandırır.</p><h3>4. Yulaf</h3><p>Kompleks karbonhidrat kaynağı. Antrenman öncesi enerji sağlar ve kas glikojen depolarını doldurur.</p><h3>5. Süzme Peynir (Quark)</h3><p>Kazein proteini bakımından zengin. Yavaş emilen yapısıyla gece boyunca kas onarımını destekler.</p><h3>6. Kırmızı Et</h3><p>Demir, çinko, B12 vitamini ve kreatin doğal kaynağıdır. Haftada 2-3 porsiyon önerilir.</p><h3>7. Badem</h3><p>Sağlıklı yağlar, E vitamini ve magnezyum içerir. Kalori yoğunluğu kilo almak isteyenler için avantajdır.</p><h3>8. Brokoli</h3><p>Antioksidanlar ve C vitamini bakımından zengin. Kortizol seviyesini dengelemeye yardımcı olur.</p><h3>9. Tatlı Patates</h3><p>Kompleks karbonhidrat ve beta-karoten kaynağı. Antrenman sonrası glikojen yenileme için idealdir.</p><h3>10. Lor Peyniri</h3><p>Düşük kalorili, yüksek proteinli Türk mutfağının süper besini. 100g'da yaklaşık 12g protein bulunur.</p>`,
      coverImage: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800",
      categoryId: beslenmeC?.id || null,
      authorId: null,
      authorName: "FitSupp Uzman Ekibi",
      authorAvatar: null,
      tags: ["beslenme", "kas-yapimi", "protein", "diyet"],
      readingTime: 4,
      isPublished: true,
      isFeatured: false,
      publishedAt: new Date(),
    },
    {
      title: "Kreatin Kullanım Rehberi: Yükleme Gerekli mi?",
      slug: "kreatin-kullanim-rehberi",
      excerpt: "Kreatin monohidrat nedir, nasıl kullanılır, yükleme fazı gerekli midir? Bilimsel verilerle kreatin rehberi.",
      content: `<h2>Kreatin: Bilimsel Rehber</h2><p>Kreatin, spor takviyesi dünyasında en çok araştırılmış ve etkinliği kanıtlanmış supplement'tir. ISSN (International Society of Sports Nutrition) tarafından güvenli ve etkili olarak sınıflandırılmıştır.</p><h3>Kreatin Ne İşe Yarar?</h3><p>Kreatin, kaslarınızdaki ATP (adenozin trifosfat) üretimini artırarak:</p><ul><li>Kısa süreli yüksek yoğunluklu egzersiz performansını artırır</li><li>Kas kuvvetini ve gücünü destekler</li><li>Kas hacmini artırır (hücre içi su tutulumu)</li><li>Toparlanmayı hızlandırır</li></ul><h3>Yükleme Fazı Gerekli mi?</h3><p>Kısa cevap: Hayır, zorunlu değil.</p><p><strong>Yükleme protokolü:</strong> 7 gün boyunca günde 20g (4x5g), ardından günde 3-5g idame dozu. Kreatin depolarını 5-7 günde doldurur.</p><p><strong>Yüklemesiz protokol:</strong> Günde 3-5g sürekli kullanım. Kreatin depolarını 3-4 haftada doldurur. Sindirim problemleri daha azdır.</p><h3>Ne Zaman Alınmalı?</h3><p>Kreatin zamanlama bağımsızdır. Günün herhangi bir saatinde alabilirsiniz. Ancak araştırmalar antrenman sonrası alımın marjinal olarak daha etkili olabileceğini göstermektedir.</p><h3>Yan Etkileri</h3><p>Kreatin genel olarak güvenlidir. En yaygın yan etki ilk haftalarda görülen su tutulumudur (1-3kg). Yeterli su tüketimi (günde 3+ litre) önerilir.</p>`,
      coverImage: "https://images.unsplash.com/photo-1594381898411-846e7d193883?w=800",
      categoryId: supplementC?.id || null,
      authorId: null,
      authorName: "FitSupp Uzman Ekibi",
      authorAvatar: null,
      tags: ["kreatin", "supplement", "performans", "rehber"],
      readingTime: 5,
      isPublished: true,
      isFeatured: false,
      publishedAt: new Date(),
    },
    {
      title: "Antrenman Sonrası Toparlanma Stratejileri",
      slug: "antrenman-sonrasi-toparlanma",
      excerpt: "Kas gelişiminin %70'i toparlanma döneminde gerçekleşir. En etkili recovery stratejileri ve beslenme önerileri.",
      content: `<h2>Toparlanma Neden Bu Kadar Önemli?</h2><p>Antrenman sırasında kaslarınız mikro hasarlar alır. Asıl kas yapımı, bu hasarların onarıldığı toparlanma döneminde gerçekleşir. Yetersiz toparlanma, overtraining sendromuna ve sakatlanmalara yol açabilir.</p><h3>1. Beslenme Stratejisi</h3><p><strong>Antrenman sonrası ilk 30 dakika:</strong> 20-40g whey protein + 40-60g hızlı emilen karbonhidrat (muz, pirinç keki gibi). Bu anabolik pencereyi en verimli şekilde değerlendirmenizi sağlar.</p><h3>2. Uyku</h3><p>Kas onarımı büyük ölçüde uyku sırasında gerçekleşir. Growth hormone (büyüme hormonu) salınımı derin uyku fazında zirve yapar. Hedef: Günde 7-9 saat kaliteli uyku.</p><h3>3. Aktif Toparlanma</h3><p>Tam dinlenme günlerinde hafif kardiyo (yürüyüş, yüzme) veya esneme yapın. Bu, kan dolaşımını artırarak besin taşınımını hızlandırır.</p><h3>4. Supplement Desteği</h3><ul><li><strong>BCAA:</strong> Kas protein sentezini uyarır, kas yıkımını azaltır</li><li><strong>Glutamin:</strong> Bağışıklık sistemini destekler, kas toparlanmasını hızlandırır</li><li><strong>Omega-3:</strong> Anti-inflamatuar etki ile kas ağrılarını azaltır</li><li><strong>Magnezyum:</strong> Kas kramplarını önler, uyku kalitesini artırır</li></ul><h3>5. Hidrasyon</h3><p>Antrenman sırasında kaybedilen sıvıyı yerine koyun. Genel kural: Kilogram başına 35-40ml su tüketin. Antrenman sonrası ek olarak 500ml-1 litre su için.</p>`,
      coverImage: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800",
      categoryId: saglikC?.id || null,
      authorId: null,
      authorName: "FitSupp Uzman Ekibi",
      authorAvatar: null,
      tags: ["toparlanma", "recovery", "antrenman", "saglik"],
      readingTime: 5,
      isPublished: true,
      isFeatured: true,
      publishedAt: new Date(),
    },
  ]);

  console.log("Database seeded successfully!");
}
